/// Types of voice alerts generated by the assistant state machine.
enum VoiceAlertType {
  /// Trigger 1: Speed limit decreases below 50 km/h (e.g. 30 km/h or 40 km/h zone)
  speedReduced,

  /// Trigger 2: Speed limit returns to 50 km/h or more (speed zone ended)
  speedZoneEnded,

  /// Trigger 3: Vehicle enters a one-way street (oneway == true)
  oneWayEntered,

  /// Trigger 4: Vehicle exits a one-way street (oneway == false)
  oneWayExited,

  /// Trigger 5: Vehicle enters a living street / residential zone (20 km/h)
  livingStreetEntered,

  /// Trigger 6: Dynamic street name / speed limit announcement
  streetChanged,

  /// Trigger 7: Vehicle enters a 30 km/h speed limit zone
  speed30ZoneEntered,

  /// Trigger 8: Speed limit restored to normal (e.g. 50 km/h) after an isolated reduced speed section (not a zone)
  speedRestored,

  /// Trigger 9: Vehicle exceeds speed limit + tolerance
  speedingWarning,

  /// Trigger 10: User enters a bicycle or pedestrian path
  pedestrianOrBicycleWayEntered,

  /// Trigger 11: Lookahead lower speed zone warning (e.g. 50-100m ahead)
  lookaheadSpeedReduced,

  /// Trigger 12: Upcoming traffic calming / speed bump
  trafficCalmingAhead,

  /// Trigger 13: Upcoming stationary speed enforcement camera
  speedCameraAhead,

  /// Trigger 14: Lookahead traffic light warning
  trafficLightAhead,

  /// Trigger 15: Lookahead give way warning
  giveWayAhead,

  /// Trigger 16: Lookahead main road reminder
  mainRoadReminder,

  /// Trigger 17: Lookahead equal intersection warning
  equalIntersectionAhead,

  /// Trigger 18: Lookahead main road turns warning
  mainRoadTurns,

  /// Trigger 19: Lookahead speed restriction end warning (e.g. 30 -> 50)
  lookaheadSpeedRestored,
}

/// Represents an alert event with the exact Latvian announcement text.
class VoiceAlertEvent {
  final VoiceAlertType type;
  final String spokenText;
  final DateTime timestamp;
  final int? speedLimitKmh;
  final bool? isOneWay;
  final String? streetName;

  const VoiceAlertEvent({
    required this.type,
    required this.spokenText,
    required this.timestamp,
    this.speedLimitKmh,
    this.isOneWay,
    this.streetName,
  });

  @override
  String toString() {
    return 'VoiceAlertEvent(type: $type, text: "$spokenText", time: $timestamp)';
  }
}
