/// Types of voice alerts generated by the assistant state machine.
enum VoiceAlertType {
  /// Trigger 1: Speed limit decreases below 50 km/h (e.g. 30 km/h or 40 km/h zone)
  speedReduced,

  /// Trigger 2: Speed limit returns to 50 km/h or more (speed zone ended)
  speedZoneEnded,

  /// Trigger 3: Vehicle enters a one-way street (oneway == true)
  oneWayEntered,

  /// Trigger 4: Vehicle exits a one-way street (oneway == false)
  oneWayExited,
}

/// Represents an alert event with the exact Latvian announcement text.
class VoiceAlertEvent {
  final VoiceAlertType type;
  final String spokenText;
  final DateTime timestamp;
  final int? speedLimitKmh;
  final bool? isOneWay;
  final String? streetName;

  const VoiceAlertEvent({
    required this.type,
    required this.spokenText,
    required this.timestamp,
    this.speedLimitKmh,
    this.isOneWay,
    this.streetName,
  });

  @override
  String toString() {
    return 'VoiceAlertEvent(type: $type, text: "$spokenText", time: $timestamp)';
  }
}
